version: '3.8'

networks:
  frontend:
  backend:
# Services
services:

    # PHP Service
    php:
        build:
            dockerfile: php-dockerfile
        volumes:
            - './php-files:/var/www/html'
        depends_on:
            - mysql
        networks:
          - backend

    # Nginx Service
    nginx:
        image: nginx:latest
        ports:
            - 4001:80
        links:
            - 'php'
        volumes:
            - './php-files:/var/www/html'
            - './nginx-conf:/etc/nginx/conf.d'
        depends_on:
            - php
        networks:
            - frontend
            - backend

    # MariaDB Service
    mysql:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: makaron
            MYSQL_DATABASE: testdb
            MYSQL_USER: testuser
            MYSQL_PASSWORD: testpass
        volumes:
            - mysqldata:/var/lib/mysql
        networks:
            - backend

    # phpMyAdmin Service
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - 6001:80
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: rootpass
        depends_on:
            - mysql
        networks:
            - backend
            - frontend

# Volumes
volumes:

  mysqldata: